feat(lightswitch): deploy to prod if conditions are met

diff --git a/.github/workflows/lightswitch_deploy_run.yaml b/.github/workflows/lightswitch_deploy_run.yaml
--- a/.github/workflows/lightswitch_deploy_run.yaml
+++ b/.github/workflows/lightswitch_deploy_run.yaml
@@ -1,29 +1,46 @@
 name: Lightswitch Deploy & Run
 
 on:
-  workflow_run:
-    workflows: ["Deploy to Staging", "Deploy to Production"]
-    types: [completed]
+  push:
+    branches:
+      - main
     paths:
       - 'src/lamp_py/publishing/lightswitch.py'
+    tags:
+      - '*'
     secrets:
       AWS_ROLE_ARN:
         description: AWS_ROLE_ARN
         required: true
 
 jobs:
+  check-tag:
+    runs-on: ubuntu-latest
+    if: ${{ github.ref_type == 'tag' }}
+    steps:
+      - name: Check Semantic Version Format
+        run: |
+          TAG_NAME="${{ github.ref_name }}"
+          if [[ "$TAG_NAME" =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+            echo "Tag '$TAG_NAME' valid semantic version."
+          else
+            echo "Deploy to Production not executed - tags must follow semantic versioning. |
+             (e.g. v1.2.3) '$TAG_NAME' does NOT follow semantic versioning."
+            exit 1
+          fi
   deploy:
+    # if the job was triggered by a push or it was triggered by a tag and the preceding task didn't fail
+    if: ${{ github.ref_type != 'tag' || !failure() }}
     uses: ./.github/workflows/deploy-base.yaml
     with:
-      # pass the inputs from the workflow dispatch through to the deploy base. the booleans are
-      # converted to strings, so flip them back using fromJson function
-      environment: staging
+      # if the trigger is a tag then deploy to prod; otherwise deploy to staging
+      environment: ${{ (github.ref_type == 'tag' && 'prod') || 'staging' }}
       deploy-lightswitch: true
     secrets: inherit
   run_lightswitch_task:
     needs: deploy
     uses: ./.github/workflows/run-task.yaml
     with:
-      environment: staging
+      environment: ${{ (github.ref_type == 'tag' && 'prod') || 'staging' }}
       task: Lightswitch
     secrets: inherit
